export interface Project {
  id: number;
  slug: string;
  title: string;
  description: string;
  category: 'Client' | 'Personal';
  techStack: string[];
  projectUrl: string;
  siteUrl: string;
  tags: string[];
  modalKind?: 'gallery' | 'pdf';
  modalAssets?: string[];
  externalUrl?: string;
}

export const initialProjects: Project[] = [
  {
    id: 1,
    slug: 'architectural-visualization-project',
    title: 'Architectural Visualization Project',
    description:
      'Created a realistic architectural visualization and animation of a structural design using Unreal Engine. All 3D assets were sourced from Fab Lab. The project focused on lighting, camera movement, and immersive walkthroughs to convey design intent.',
    category: 'Personal',
    techStack: ['Unreal Engine', 'Premier Pro', '3ds Max', 'Adobe Media Encode'],
    projectUrl: '/projects/architectural-visualization-project',
    siteUrl: 'View project',
    tags: ['Visualization', 'Animation', 'Personal'],
    externalUrl: 'https://www.youtube.com/watch?v=Zt2Q7511Jzk',
  },
  {
    id: 2,
    slug: 'soda-can-commercial',
    title: 'Soda Can Commercial',
    description:
      'Produced a complete 3D commercial featuring an animated soda can. From UV-mapped textures to realistic lighting and smooth post-composition, the project blended multiple tools and disciplines for a dynamic product showcase.',
    category: 'Personal',
    techStack: ['Maya', 'Canva', 'V-Ray', 'After Effects', 'Premiere Pro', 'Adobe Media Encoder'],
    projectUrl: '/projects/soda-can-commercial',
    siteUrl: 'View project',
    tags: ['3D Animation', 'Motion Graphics', 'Personal'],
    externalUrl: 'https://www.youtube.com/watch?v=4Va01hofghA',
  },
  {
    id: 3,
    slug: 'mct-landing-page-enhanced',
    title: 'MCT Landing Page (Enhanced)',
    description:
      'Created and Revamped the Multimedia and Creative Technology (MCT) department landing page by integrating an AI-powered chatbot using Botpress AI-powered voice assistance using Elevenlabs Conversational AI and immersive AR/VR features through Convai.',
    category: 'Personal',
    techStack: ['HTML', 'CSS', 'JavaScript', 'Bootstrap', 'Botpress', 'Elevenlabs', 'Convai', 'Unity'],
    projectUrl: '/projects/mct-landing-page-enhanced',
    siteUrl: 'View project',
    tags: ['Web Development', 'AI', 'Personal'],
    externalUrl: 'https://dsh-mahi.github.io/multimedia-and-creative-technology/',
  },
  {
    id: 4,
    slug: 'seo-optimization-sip-hygiene',
    title: 'SEO Optimization - Sip Hygiene',
    description:
      'Achieved first-page rankings for multiple articles on a water bottle review website through strategic on-page SEO. Boosted article scores to 89-98/100 using keyword targeting, schema markup, and internal linking. Also optimized site performance to score 100/100 on mobile and 99/100 on desktop.',
    category: 'Personal',
    techStack: ['WordPress', 'Google PageSpeed Insights', 'Rank Math SEO', 'Schema Markup', 'Google Search Console'],
    projectUrl: '/projects/seo-optimization-sip-hygiene',
    siteUrl: 'View project',
    tags: ['SEO', 'Performance Tuning', 'Personal'],
    modalKind: 'gallery',
    modalAssets: [
      '/SEO/Perfect Desktop Optimization_.jpg',
      '/SEO/Perfect Mobile Optimization_.jpg',
      '/SEO/Perfect SEO optimized Contents.jpg',
      '/SEO/Perfect SEO optimized Content_.jpg',
      '/SEO/Ranking 1st page on google.jpg',
      '/SEO/Ranking First page on google.jpg',
      '/SEO/Ranking _0_ on Google.jpg',
    ],
  },
  {
    id: 5,
    slug: 'social-media-post-design',
    title: 'Social Media Post Design',
    description:
      'A curated set of social media creatives made for campaigns and promotions using Adobe Illustrator and Adobe Photoshop.',
    category: 'Personal',
    techStack: ['Adobe Illustrator', 'Adobe Photoshop'],
    projectUrl: '/projects/social-media-post-design',
    siteUrl: 'View project',
    tags: ['Social Media Design', 'Marketing', 'Personal'],
    modalKind: 'gallery',
    modalAssets: [
      '/Social media post design/Bronze-service.jpg',
      '/Social media post design/gold-service.jpg',
      '/Social media post design/poll-post.png',
      '/Social media post design/Poster.png',
      '/Social media post design/silver-service.jpg',
      '/Social media post design/sunglass social post 02.png',
      '/Social media post design/Sunglass social post.png',
      '/Social media post design/Travel agency post.jpg',
      '/Social media post design/Ui-poll.png',
      '/Social media post design/World Environemnt day Concept 01.jpg',
      '/Social media post design/World Environemnt day Concept 02.jpg',
      '/Social media post design/World Environemnt day Concept 03.jpg',
    ],
  },
  {
    id: 6,
    slug: 'ui-ux-subscription-platform',
    title: 'UI-UX Subscription Platform',
    description:
      'A subscription-based platform UI/UX exploration designed with Figma and Galileo AI, from concept screens to polished interface flows.',
    category: 'Personal',
    techStack: ['Figma', 'Galileo AI'],
    projectUrl: '/projects/ui-ux-subscription-platform',
    siteUrl: 'View project',
    tags: ['UI/UX', 'Product Design', 'Personal'],
    modalKind: 'gallery',
    modalAssets: [
      '/UI-UX/1.jpg',
      '/UI-UX/2.jpg',
      '/UI-UX/3.png',
      '/UI-UX/4.png',
      '/UI-UX/5.png',
      '/UI-UX/6.png',
      '/UI-UX/7.png',
      '/UI-UX/8.png',
      '/UI-UX/9.png',
      '/UI-UX/10.png',
      '/UI-UX/11.png',
    ],
  },
  {
    id: 7,
    slug: 'print-design-showcase',
    title: 'Print Design Showcase',
    description:
      'A collection of print materials including brochures, invoices, and letterhead concepts created with Illustrator and Photoshop.',
    category: 'Personal',
    techStack: ['Adobe Illustrator', 'Adobe Photoshop'],
    projectUrl: '/projects/print-design-showcase',
    siteUrl: 'View project',
    tags: ['Print Design', 'Brand Materials', 'Personal'],
    modalKind: 'gallery',
    modalAssets: [
      '/Print design/Bifold Broucher Design Mockup.jpg',
      '/Print design/Bifold Broucher Design Mockup 2.jpg',
      '/Print design/Bifold Broucher Design Mockup 3.jpg',
      '/Print design/Bifold Broucher Design.jpg',
      '/Print design/imcoice-mockup.jpg',
      '/Print design/invoice-mockup-2.jpg',
      '/Print design/letterhead mockup.jpg',
      '/Print design/letterhead mockup 2.jpg',
      '/Print design/letterhead mockup 3.jpg',
      '/Print design/letterhead mockup 4.jpg',
      '/Print design/letterhead mockup 05.jpg',
      '/Print design/bel Broucher demo.pdf',
      '/Print design/Invoice Design 2026.pdf',
      '/Print design/PAD DESIGN 2026.pdf',
    ],
  },
  {
    id: 8,
    slug: 'arambor-brand-design',
    title: 'Arambor Brand Design',
    description:
      'Complete fashion brand identity presentation including logo usage, brand system, and visual identity direction.',
    category: 'Personal',
    techStack: ['Adobe Illustrator', 'Adobe Photoshop'],
    projectUrl: '/projects/arambor-brand-design',
    siteUrl: 'View project',
    tags: ['Logo Design', 'Brand Identity', 'Fashion', 'Personal'],
    modalKind: 'pdf',
    modalAssets: ['/logo design/Arambor Brand Identity.pdf'],
  },
  {
    id: 9,
    slug: 'pulling-top-brand-design',
    title: 'Pulling Top Brand Design',
    description:
      'Digital marketing agency logo design and brand identity deck covering mark exploration and brand applications.',
    category: 'Personal',
    techStack: ['Adobe Illustrator', 'Adobe Photoshop'],
    projectUrl: '/projects/pulling-top-brand-design',
    siteUrl: 'View project',
    tags: ['Logo Design', 'Brand Identity', 'Agency', 'Personal'],
    modalKind: 'pdf',
    modalAssets: ['/logo design/PULLING TOP.pdf'],
  },
  {
    id: 10,
    slug: 'sheba-brand-design',
    title: 'Sheba Brand Design',
    description:
      'Real estate agency brand logo and identity concept showcasing logo variants and branding applications.',
    category: 'Personal',
    techStack: ['Adobe Illustrator', 'Adobe Photoshop'],
    projectUrl: '/projects/sheba-brand-design',
    siteUrl: 'View project',
    tags: ['Logo Design', 'Brand Identity', 'Real Estate', 'Personal'],
    modalKind: 'pdf',
    modalAssets: ['/logo design/Sheba Brand Logo.pdf'],
  },
  {
    id: 11,
    slug: 'sheltereme-brand-design',
    title: 'Sheltereme Brand Design',
    description:
      'Real estate agency brand logo and identity project with complete brand presentation and usage examples.',
    category: 'Personal',
    techStack: ['Adobe Illustrator', 'Adobe Photoshop'],
    projectUrl: '/projects/sheltereme-brand-design',
    siteUrl: 'View project',
    tags: ['Logo Design', 'Brand Identity', 'Real Estate', 'Personal'],
    modalKind: 'pdf',
    modalAssets: ['/logo design/sheltereme properties brand identity.pdf'],
  },
  {
    id: 12,
    slug: 'fashion-brand-promo-video',
    title: 'Fashion Brand Promo Video',
    description:
      'A fashion brand promotional video edit focused on motion graphics, animation timing, and ad-style visual storytelling.',
    category: 'Personal',
    techStack: ['Adobe After Effects', 'Adobe Premiere Pro'],
    projectUrl: '/projects/fashion-brand-promo-video',
    siteUrl: 'View project',
    tags: ['Video Editing', 'Motion Graphics', 'Animation', 'Personal'],
    externalUrl: 'https://youtu.be/8nuEfk98oWg',
  },
  {
    id: 13,
    slug: 'video-resume-project',
    title: 'Video Resume Project',
    description:
      'A personal video resume crafted with motion graphics and clean pacing to present profile highlights in a concise format.',
    category: 'Personal',
    techStack: ['Adobe After Effects', 'Adobe Premiere Pro'],
    projectUrl: '/projects/video-resume-project',
    siteUrl: 'View project',
    tags: ['Video Editing', 'Motion Graphics', 'Animation', 'Personal'],
    externalUrl: 'https://youtu.be/RpLJfQVd4YY',
  },
  {
    id: 14,
    slug: '2d-animator-portfolio-website',
    title: '2D Animator Portfolio Website',
    description:
      'Designed and developed a portfolio website for a 2D animator with a simple, personality-aligned presentation of animation work.',
    category: 'Client',
    techStack: ['HTML', 'CSS', 'JavaScript', 'AI-assisted ideation'],
    projectUrl: '/projects/2d-animator-portfolio-website',
    siteUrl: 'View project',
    tags: ['Web Development', 'UI/UX', 'Portfolio', 'Client'],
    externalUrl: 'https://galibabdullah.vercel.app/',
  },
  {
    id: 15,
    slug: 'vr-90s-school-game',
    title: 'VR 90s School Game',
    description:
      'A Unity VR game set in a 90s classroom atmosphere where players collect a cricket bat and ball within a time limit to score points.',
    category: 'Personal',
    techStack: ['Unity', 'VR Development', 'Game Design'],
    projectUrl: '/projects/vr-90s-school-game',
    siteUrl: 'View project',
    tags: ['VR Game', 'Unity', 'Interactive', 'Personal'],
    externalUrl: 'https://dsh-mahi.itch.io/vr-90s-school',
  },
  {
    id: 16,
    slug: 'virtual-horse-market',
    title: 'Virtual Horse Market',
    description:
      'A third-person Unity game featuring a riverside village fair where users explore stalls, check horse prices, and interact with characters.',
    category: 'Personal',
    techStack: ['Unity', 'Mixamo', 'AI Animation'],
    projectUrl: '/projects/virtual-horse-market',
    siteUrl: 'View project',
    tags: ['Game Development', 'Unity', '3D', 'Personal'],
    externalUrl: 'https://dsh-mahi.itch.io/virtual-horse-market',
  },
  {
    id: 17,
    slug: 'ar-alphabet-learning-app',
    title: 'AR Alphabet Learning App',
    description:
      'An AR learning app built with Unity AR and Vuforia where users scan alphabet letters (A, B, C, D) to reveal related 3D models and meanings.',
    category: 'Personal',
    techStack: ['Unity AR', 'Vuforia', '3D Interaction'],
    projectUrl: '/projects/ar-alphabet-learning-app',
    siteUrl: 'View project',
    tags: ['AR App', 'Unity', 'Education', 'Personal'],
    externalUrl: 'https://youtu.be/5vwaPYfOEaI',
  },
  {
    id: 18,
    slug: 'flappy-bird-recreation-2d',
    title: 'Flappy Bird Recreation (2D)',
    description:
      'A 2D Flappy Bird-style game recreated in Unity with platformer-style mechanics, obstacle timing, and score-based gameplay.',
    category: 'Personal',
    techStack: ['Unity 2D', 'Game Development'],
    projectUrl: '/projects/flappy-bird-recreation-2d',
    siteUrl: 'View project',
    tags: ['2D Game', 'Unity', 'Gameplay', 'Personal'],
    externalUrl: 'https://youtu.be/A4WZr7IRTfg',
  },
];
